export const countries = [
	{ id: 1, name: "Afghanistan", phone_code: "93", emoji: "🇦🇫" },
	{ id: 2, name: "Aland Islands", phone_code: "358", emoji: "🇦🇽" },
	{ id: 3, name: "Albania", phone_code: "355", emoji: "🇦🇱" },
	{ id: 4, name: "Algeria", phone_code: "213", emoji: "🇩🇿" },
	{ id: 5, name: "American Samoa", phone_code: "1", emoji: "🇦🇸" },
	{ id: 6, name: "Andorra", phone_code: "376", emoji: "🇦🇩" },
	{ id: 7, name: "Angola", phone_code: "244", emoji: "🇦🇴" },
	{ id: 8, name: "Anguilla", phone_code: "1", emoji: "🇦🇮" },
	{ id: 9, name: "Antarctica", phone_code: "672", emoji: "🇦🇶" },
	{
		id: 10,
		name: "Antigua And Barbuda",
		phone_code: "1",
		emoji: "🇦🇬",
	},
	{ id: 11, name: "Argentina", phone_code: "54", emoji: "🇦🇷" },
	{ id: 12, name: "Armenia", phone_code: "374", emoji: "🇦🇲" },
	{ id: 13, name: "Aruba", phone_code: "297", emoji: "🇦🇼" },
	{ id: 14, name: "Australia", phone_code: "61", emoji: "🇦🇺" },
	{ id: 15, name: "Austria", phone_code: "43", emoji: "🇦🇹" },
	{ id: 16, name: "Azerbaijan", phone_code: "994", emoji: "🇦🇿" },
	{ id: 18, name: "Bahrain", phone_code: "973", emoji: "🇧🇭" },
	{ id: 19, name: "Bangladesh", phone_code: "880", emoji: "🇧🇩" },
	{ id: 20, name: "Barbados", phone_code: "1", emoji: "🇧🇧" },
	{ id: 21, name: "Belarus", phone_code: "375", emoji: "🇧🇾" },
	{ id: 22, name: "Belgium", phone_code: "32", emoji: "🇧🇪" },
	{ id: 23, name: "Belize", phone_code: "501", emoji: "🇧🇿" },
	{ id: 24, name: "Benin", phone_code: "229", emoji: "🇧🇯" },
	{ id: 25, name: "Bermuda", phone_code: "1", emoji: "🇧🇲" },
	{ id: 26, name: "Bhutan", phone_code: "975", emoji: "🇧🇹" },
	{ id: 27, name: "Bolivia", phone_code: "591", emoji: "🇧🇴" },
	{
		id: 155,
		name: "Bonaire, Sint Eustatius and Saba",
		phone_code: "599",
		emoji: "🇧🇶",
	},
	{
		id: 28,
		name: "Bosnia and Herzegovina",
		phone_code: "387",
		emoji: "🇧🇦",
	},
	{ id: 29, name: "Botswana", phone_code: "267", emoji: "🇧🇼" },
	{ id: 30, name: "Bouvet Island", phone_code: "0055", emoji: "🇧🇻" },
	{ id: 31, name: "Brazil", phone_code: "55", emoji: "🇧🇷" },
	{
		id: 32,
		name: "British Indian Ocean Territory",
		phone_code: "246",
		emoji: "🇮🇴",
	},
	{ id: 33, name: "Brunei", phone_code: "673", emoji: "🇧🇳" },
	{ id: 34, name: "Bulgaria", phone_code: "359", emoji: "🇧🇬" },
	{ id: 35, name: "Burkina Faso", phone_code: "226", emoji: "🇧🇫" },
	{ id: 36, name: "Burundi", phone_code: "257", emoji: "🇧🇮" },
	{ id: 37, name: "Cambodia", phone_code: "855", emoji: "🇰🇭" },
	{ id: 38, name: "Cameroon", phone_code: "237", emoji: "🇨🇲" },
	{ id: 39, name: "Canada", phone_code: "1", emoji: "🇨🇦" },
	{ id: 40, name: "Cape Verde", phone_code: "238", emoji: "🇨🇻" },
	{ id: 41, name: "Cayman Islands", phone_code: "1", emoji: "🇰🇾" },
	{
		id: 42,
		name: "Central African Republic",
		phone_code: "236",
		emoji: "🇨🇫",
	},
	{ id: 43, name: "Chad", phone_code: "235", emoji: "🇹🇩" },
	{ id: 44, name: "Chile", phone_code: "56", emoji: "🇨🇱" },
	{ id: 45, name: "China", phone_code: "86", emoji: "🇨🇳" },
	{ id: 46, name: "Christmas Island", phone_code: "61", emoji: "🇨🇽" },
	{
		id: 47,
		name: "Cocos (Keeling) Islands",
		phone_code: "61",
		emoji: "🇨🇨",
	},
	{ id: 48, name: "Colombia", phone_code: "57", emoji: "🇨🇴" },
	{ id: 49, name: "Comoros", phone_code: "269", emoji: "🇰🇲" },
	{ id: 50, name: "Congo", phone_code: "242", emoji: "🇨🇬" },
	{ id: 52, name: "Cook Islands", phone_code: "682", emoji: "🇨🇰" },
	{ id: 53, name: "Costa Rica", phone_code: "506", emoji: "🇨🇷" },
	{
		id: 54,
		name: "Cote D'Ivoire (Ivory Coast)",
		phone_code: "225",
		emoji: "🇨🇮",
	},
	{ id: 55, name: "Croatia", phone_code: "385", emoji: "🇭🇷" },
	{ id: 56, name: "Cuba", phone_code: "53", emoji: "🇨🇺" },
	{ id: 249, name: "Curaçao", phone_code: "599", emoji: "🇨🇼" },
	{ id: 57, name: "Cyprus", phone_code: "357", emoji: "🇨🇾" },
	{ id: 58, name: "Czech Republic", phone_code: "420", emoji: "🇨🇿" },
	{
		id: 51,
		name: "Democratic Republic of the Congo",
		phone_code: "243",
		emoji: "🇨🇩",
	},
	{ id: 59, name: "Denmark", phone_code: "45", emoji: "🇩🇰" },
	{ id: 60, name: "Djibouti", phone_code: "253", emoji: "🇩🇯" },
	{ id: 61, name: "Dominica", phone_code: "1", emoji: "🇩🇲" },
	{
		id: 62,
		name: "Dominican Republic",
		phone_code: "1",
		emoji: "🇩🇴",
	},
	{ id: 63, name: "East Timor", phone_code: "670", emoji: "🇹🇱" },
	{ id: 64, name: "Ecuador", phone_code: "593", emoji: "🇪🇨" },
	{ id: 65, name: "Egypt", phone_code: "20", emoji: "🇪🇬" },
	{ id: 66, name: "El Salvador", phone_code: "503", emoji: "🇸🇻" },
	{
		id: 67,
		name: "Equatorial Guinea",
		phone_code: "240",
		emoji: "🇬🇶",
	},
	{ id: 68, name: "Eritrea", phone_code: "291", emoji: "🇪🇷" },
	{ id: 69, name: "Estonia", phone_code: "372", emoji: "🇪🇪" },
	{ id: 70, name: "Ethiopia", phone_code: "251", emoji: "🇪🇹" },
	{
		id: 71,
		name: "Falkland Islands",
		phone_code: "500",
		emoji: "🇫🇰",
	},
	{ id: 72, name: "Faroe Islands", phone_code: "298", emoji: "🇫🇴" },
	{ id: 73, name: "Fiji Islands", phone_code: "679", emoji: "🇫🇯" },
	{ id: 74, name: "Finland", phone_code: "358", emoji: "🇫🇮" },
	{ id: 75, name: "France", phone_code: "33", emoji: "🇫🇷" },
	{ id: 76, name: "French Guiana", phone_code: "594", emoji: "🇬🇫" },
	{
		id: 77,
		name: "French Polynesia",
		phone_code: "689",
		emoji: "🇵🇫",
	},
	{
		id: 78,
		name: "French Southern Territories",
		phone_code: "262",
		emoji: "🇹🇫",
	},
	{ id: 79, name: "Gabon", phone_code: "241", emoji: "🇬🇦" },
	{ id: 80, name: "Gambia The", phone_code: "220", emoji: "🇬🇲" },
	{ id: 81, name: "Georgia", phone_code: "995", emoji: "🇬🇪" },
	{ id: 82, name: "Germany", phone_code: "49", emoji: "🇩🇪" },
	{ id: 83, name: "Ghana", phone_code: "233", emoji: "🇬🇭" },
	{ id: 84, name: "Gibraltar", phone_code: "350", emoji: "🇬🇮" },
	{ id: 85, name: "Greece", phone_code: "30", emoji: "🇬🇷" },
	{ id: 86, name: "Greenland", phone_code: "299", emoji: "🇬🇱" },
	{ id: 87, name: "Grenada", phone_code: "1", emoji: "🇬🇩" },
	{ id: 88, name: "Guadeloupe", phone_code: "590", emoji: "🇬🇵" },
	{ id: 89, name: "Guam", phone_code: "1", emoji: "🇬🇺" },
	{ id: 90, name: "Guatemala", phone_code: "502", emoji: "🇬🇹" },
	{
		id: 91,
		name: "Guernsey and Alderney",
		phone_code: "44",
		emoji: "🇬🇬",
	},
	{ id: 92, name: "Guinea", phone_code: "224", emoji: "🇬🇳" },
	{ id: 93, name: "Guinea-Bissau", phone_code: "245", emoji: "🇬🇼" },
	{ id: 94, name: "Guyana", phone_code: "592", emoji: "🇬🇾" },
	{ id: 95, name: "Haiti", phone_code: "509", emoji: "🇭🇹" },
	{
		id: 96,
		name: "Heard Island and McDonald Islands",
		phone_code: "672",
		emoji: "🇭🇲",
	},
	{ id: 97, name: "Honduras", phone_code: "504", emoji: "🇭🇳" },
	{ id: 98, name: "Hong Kong ", phone_code: "852", emoji: "🇭🇰" },
	{ id: 99, name: "Hungary", phone_code: "36", emoji: "🇭🇺" },
	{ id: 100, name: "Iceland", phone_code: "354", emoji: "🇮🇸" },
	{ id: 101, name: "India", phone_code: "91", emoji: "🇮🇳" },
	{ id: 102, name: "Indonesia", phone_code: "62", emoji: "🇮🇩" },
	{ id: 103, name: "Iran", phone_code: "98", emoji: "🇮🇷" },
	{ id: 104, name: "Iraq", phone_code: "964", emoji: "🇮🇶" },
	{ id: 105, name: "Ireland", phone_code: "353", emoji: "🇮🇪" },
	{ id: 106, name: "Israel", phone_code: "972", emoji: "🇮🇱" },
	{ id: 107, name: "Italy", phone_code: "39", emoji: "🇮🇹" },
	{ id: 108, name: "Jamaica", phone_code: "1", emoji: "🇯🇲" },
	{ id: 109, name: "Japan", phone_code: "81", emoji: "🇯🇵" },
	{ id: 110, name: "Jersey", phone_code: "44", emoji: "🇯🇪" },
	{ id: 111, name: "Jordan", phone_code: "962", emoji: "🇯🇴" },
	{ id: 112, name: "Kazakhstan", phone_code: "7", emoji: "🇰🇿" },
	{ id: 113, name: "Kenya", phone_code: "254", emoji: "🇰🇪" },
	{ id: 114, name: "Kiribati", phone_code: "686", emoji: "🇰🇮" },
	{ id: 248, name: "Kosovo", phone_code: "383", emoji: "🇽🇰" },
	{ id: 117, name: "Kuwait", phone_code: "965", emoji: "🇰🇼" },
	{ id: 118, name: "Kyrgyzstan", phone_code: "996", emoji: "🇰🇬" },
	{ id: 119, name: "Laos", phone_code: "856", emoji: "🇱🇦" },
	{ id: 120, name: "Latvia", phone_code: "371", emoji: "🇱🇻" },
	{ id: 121, name: "Lebanon", phone_code: "961", emoji: "🇱🇧" },
	{ id: 122, name: "Lesotho", phone_code: "266", emoji: "🇱🇸" },
	{ id: 123, name: "Liberia", phone_code: "231", emoji: "🇱🇷" },
	{ id: 124, name: "Libya", phone_code: "218", emoji: "🇱🇾" },
	{ id: 125, name: "Liechtenstein", phone_code: "423", emoji: "🇱🇮" },
	{ id: 126, name: "Lithuania", phone_code: "370", emoji: "🇱🇹" },
	{ id: 127, name: "Luxembourg", phone_code: "352", emoji: "🇱🇺" },
	{ id: 128, name: "Macau ", phone_code: "853", emoji: "🇲🇴" },
	{ id: 130, name: "Madagascar", phone_code: "261", emoji: "🇲🇬" },
	{ id: 131, name: "Malawi", phone_code: "265", emoji: "🇲🇼" },
	{ id: 132, name: "Malaysia", phone_code: "60", emoji: "🇲🇾" },
	{ id: 133, name: "Maldives", phone_code: "960", emoji: "🇲🇻" },
	{ id: 134, name: "Mali", phone_code: "223", emoji: "🇲🇱" },
	{ id: 135, name: "Malta", phone_code: "356", emoji: "🇲🇹" },
	{ id: 136, name: "Man (Isle of)", phone_code: "44", emoji: "🇮🇲" },
	{
		id: 137,
		name: "Marshall Islands",
		phone_code: "692",
		emoji: "🇲🇭",
	},
	{ id: 138, name: "Martinique", phone_code: "596", emoji: "🇲🇶" },
	{ id: 139, name: "Mauritania", phone_code: "222", emoji: "🇲🇷" },
	{ id: 140, name: "Mauritius", phone_code: "230", emoji: "🇲🇺" },
	{ id: 141, name: "Mayotte", phone_code: "262", emoji: "🇾🇹" },
	{ id: 142, name: "Mexico", phone_code: "52", emoji: "🇲🇽" },
	{ id: 143, name: "Micronesia", phone_code: "691", emoji: "🇫🇲" },
	{ id: 144, name: "Moldova", phone_code: "373", emoji: "🇲🇩" },
	{ id: 145, name: "Monaco", phone_code: "377", emoji: "🇲🇨" },
	{ id: 146, name: "Mongolia", phone_code: "976", emoji: "🇲🇳" },
	{ id: 147, name: "Montenegro", phone_code: "382", emoji: "🇲🇪" },
	{ id: 148, name: "Montserrat", phone_code: "1", emoji: "🇲🇸" },
	{ id: 149, name: "Morocco", phone_code: "212", emoji: "🇲🇦" },
	{ id: 150, name: "Mozambique", phone_code: "258", emoji: "🇲🇿" },
	{ id: 151, name: "Myanmar", phone_code: "95", emoji: "🇲🇲" },
	{ id: 152, name: "Namibia", phone_code: "264", emoji: "🇳🇦" },
	{ id: 153, name: "Nauru", phone_code: "674", emoji: "🇳🇷" },
	{ id: 154, name: "Nepal", phone_code: "977", emoji: "🇳🇵" },
	{ id: 156, name: "Netherlands", phone_code: "31", emoji: "🇳🇱" },
	{ id: 157, name: "New Caledonia", phone_code: "687", emoji: "🇳🇨" },
	{ id: 158, name: "New Zealand", phone_code: "64", emoji: "🇳🇿" },
	{ id: 159, name: "Nicaragua", phone_code: "505", emoji: "🇳🇮" },
	{ id: 160, name: "Niger", phone_code: "227", emoji: "🇳🇪" },
	{ id: 161, name: "Nigeria", phone_code: "234", emoji: "🇳🇬" },
	{ id: 162, name: "Niue", phone_code: "683", emoji: "🇳🇺" },
	{ id: 163, name: "Norfolk Island", phone_code: "672", emoji: "🇳🇫" },
	{ id: 115, name: "North Korea", phone_code: "850", emoji: "🇰🇵" },
	{
		id: 129,
		name: "North Macedonia",
		phone_code: "389",
		emoji: "🇲🇰",
	},
	{
		id: 164,
		name: "Northern Mariana Islands",
		phone_code: "1",
		emoji: "🇲🇵",
	},
	{ id: 165, name: "Norway", phone_code: "47", emoji: "🇳🇴" },
	{ id: 166, name: "Oman", phone_code: "968", emoji: "🇴🇲" },
	{ id: 167, name: "Pakistan", phone_code: "92", emoji: "🇵🇰" },
	{ id: 168, name: "Palau", phone_code: "680", emoji: "🇵🇼" },
	{
		id: 169,
		name: "Palestinian Territory Occupied",
		phone_code: "970",
		emoji: "🇵🇸",
	},
	{ id: 170, name: "Panama", phone_code: "507", emoji: "🇵🇦" },
	{
		id: 171,
		name: "Papua new Guinea",
		phone_code: "675",
		emoji: "🇵🇬",
	},
	{ id: 172, name: "Paraguay", phone_code: "595", emoji: "🇵🇾" },
	{ id: 173, name: "Peru", phone_code: "51", emoji: "🇵🇪" },
	{ id: 174, name: "Philippines", phone_code: "63", emoji: "🇵🇭" },
	{
		id: 175,
		name: "Pitcairn Island",
		phone_code: "870",
		emoji: "🇵🇳",
	},
	{ id: 176, name: "Poland", phone_code: "48", emoji: "🇵🇱" },
	{ id: 177, name: "Portugal", phone_code: "351", emoji: "🇵🇹" },
	{ id: 178, name: "Puerto Rico", phone_code: "1", emoji: "🇵🇷" },
	{ id: 179, name: "Qatar", phone_code: "974", emoji: "🇶🇦" },
	{ id: 180, name: "Reunion", phone_code: "262", emoji: "🇷🇪" },
	{ id: 181, name: "Romania", phone_code: "40", emoji: "🇷🇴" },
	{ id: 182, name: "Russia", phone_code: "7", emoji: "🇷🇺" },
	{ id: 183, name: "Rwanda", phone_code: "250", emoji: "🇷🇼" },
	{ id: 184, name: "Saint Helena", phone_code: "290", emoji: "🇸🇭" },
	{
		id: 185,
		name: "Saint Kitts And Nevis",
		phone_code: "1",
		emoji: "🇰🇳",
	},
	{ id: 186, name: "Saint Lucia", phone_code: "1", emoji: "🇱🇨" },
	{
		id: 187,
		name: "Saint Pierre and Miquelon",
		phone_code: "508",
		emoji: "🇵🇲",
	},
	{
		id: 188,
		name: "Saint Vincent And The Grenadines",
		phone_code: "1",
		emoji: "🇻🇨",
	},
	{
		id: 189,
		name: "Saint-Barthelemy",
		phone_code: "590",
		emoji: "🇧🇱",
	},
	{
		id: 190,
		name: "Saint-Martin (French part)",
		phone_code: "590",
		emoji: "🇲🇫",
	},
	{ id: 191, name: "Samoa", phone_code: "685", emoji: "🇼🇸" },
	{ id: 192, name: "San Marino", phone_code: "378", emoji: "🇸🇲" },
	{
		id: 193,
		name: "Sao Tome and Principe",
		phone_code: "239",
		emoji: "🇸🇹",
	},
	{ id: 194, name: "Saudi Arabia", phone_code: "966", emoji: "🇸🇦" },
	{ id: 195, name: "Senegal", phone_code: "221", emoji: "🇸🇳" },
	{ id: 196, name: "Serbia", phone_code: "381", emoji: "🇷🇸" },
	{ id: 197, name: "Seychelles", phone_code: "248", emoji: "🇸🇨" },
	{ id: 198, name: "Sierra Leone", phone_code: "232", emoji: "🇸🇱" },
	{ id: 199, name: "Singapore", phone_code: "65", emoji: "🇸🇬" },
	{
		id: 250,
		name: "Sint Maarten (Dutch part)",
		phone_code: "1721",
		emoji: "🇸🇽",
	},
	{ id: 200, name: "Slovakia", phone_code: "421", emoji: "🇸🇰" },
	{ id: 201, name: "Slovenia", phone_code: "386", emoji: "🇸🇮" },
	{
		id: 202,
		name: "Solomon Islands",
		phone_code: "677",
		emoji: "🇸🇧",
	},
	{ id: 203, name: "Somalia", phone_code: "252", emoji: "🇸🇴" },
	{ id: 204, name: "South Africa", phone_code: "27", emoji: "🇿🇦" },
	{ id: 205, name: "South Georgia", phone_code: "500", emoji: "🇬🇸" },
	{ id: 116, name: "South Korea", phone_code: "82", emoji: "🇰🇷" },
	{ id: 206, name: "South Sudan", phone_code: "211", emoji: "🇸🇸" },
	{ id: 207, name: "Spain", phone_code: "34", emoji: "🇪🇸" },
	{ id: 208, name: "Sri Lanka", phone_code: "94", emoji: "🇱🇰" },
	{ id: 209, name: "Sudan", phone_code: "249", emoji: "🇸🇩" },
	{ id: 210, name: "Suriname", phone_code: "597", emoji: "🇸🇷" },
	{
		id: 211,
		name: "Svalbard And Jan Mayen Islands",
		phone_code: "47",
		emoji: "🇸🇯",
	},
	{ id: 212, name: "Swaziland", phone_code: "268", emoji: "🇸🇿" },
	{ id: 213, name: "Sweden", phone_code: "46", emoji: "🇸🇪" },
	{ id: 214, name: "Switzerland", phone_code: "41", emoji: "🇨🇭" },
	{ id: 215, name: "Syria", phone_code: "963", emoji: "🇸🇾" },
	{ id: 216, name: "Taiwan", phone_code: "886", emoji: "🇹🇼" },
	{ id: 217, name: "Tajikistan", phone_code: "992", emoji: "🇹🇯" },
	{ id: 218, name: "Tanzania", phone_code: "255", emoji: "🇹🇿" },
	{ id: 219, name: "Thailand", phone_code: "66", emoji: "🇹🇭" },
	{ id: 17, name: "The Bahamas", phone_code: "1", emoji: "🇧🇸" },
	{ id: 220, name: "Togo", phone_code: "228", emoji: "🇹🇬" },
	{ id: 221, name: "Tokelau", phone_code: "690", emoji: "🇹🇰" },
	{ id: 222, name: "Tonga", phone_code: "676", emoji: "🇹🇴" },
	{
		id: 223,
		name: "Trinidad And Tobago",
		phone_code: "1",
		emoji: "🇹🇹",
	},
	{ id: 224, name: "Tunisia", phone_code: "216", emoji: "🇹🇳" },
	{ id: 225, name: "Turkey", phone_code: "90", emoji: "🇹🇷" },
	{ id: 226, name: "Turkmenistan", phone_code: "993", emoji: "🇹🇲" },
	{
		id: 227,
		name: "Turks And Caicos Islands",
		phone_code: "1",
		emoji: "🇹🇨",
	},
	{ id: 228, name: "Tuvalu", phone_code: "688", emoji: "🇹🇻" },
	{ id: 229, name: "Uganda", phone_code: "256", emoji: "🇺🇬" },
	{ id: 230, name: "Ukraine", phone_code: "380", emoji: "🇺🇦" },
	{
		id: 231,
		name: "United Arab Emirates",
		phone_code: "971",
		emoji: "🇦🇪",
	},
	{ id: 232, name: "United Kingdom", phone_code: "44", emoji: "🇬🇧" },
	{ id: 233, name: "United States", phone_code: "1", emoji: "🇺🇸" },
	{
		id: 234,
		name: "United States Minor Outlying Islands",
		phone_code: "1",
		emoji: "🇺🇲",
	},
	{ id: 235, name: "Uruguay", phone_code: "598", emoji: "🇺🇾" },
	{ id: 236, name: "Uzbekistan", phone_code: "998", emoji: "🇺🇿" },
	{ id: 237, name: "Vanuatu", phone_code: "678", emoji: "🇻🇺" },
	{
		id: 238,
		name: "Vatican City State (Holy See)",
		phone_code: "379",
		emoji: "🇻🇦",
	},
	{ id: 239, name: "Venezuela", phone_code: "58", emoji: "🇻🇪" },
	{ id: 240, name: "Vietnam", phone_code: "84", emoji: "🇻🇳" },
	{
		id: 241,
		name: "Virgin Islands (British)",
		phone_code: "1",
		emoji: "🇻🇬",
	},
	{
		id: 242,
		name: "Virgin Islands (US)",
		phone_code: "1",
		emoji: "🇻🇮",
	},
	{
		id: 243,
		name: "Wallis And Futuna Islands",
		phone_code: "681",
		emoji: "🇼🇫",
	},
	{ id: 244, name: "Western Sahara", phone_code: "212", emoji: "🇪🇭" },
	{ id: 245, name: "Yemen", phone_code: "967", emoji: "🇾🇪" },
	{ id: 246, name: "Zambia", phone_code: "260", emoji: "🇿🇲" },
	{ id: 247, name: "Zimbabwe", phone_code: "263", emoji: "🇿🇼" },
];
